In [20]:
import numpy as np

# Crée un tableau temperatures de 30 valeurs simulées (entre 15 et 30 °C)
# avec un random.default_rng(seed=42)
temperatures = np.random.default_rng(seed=42).uniform(low=15, high=30,size=30)
print(f"Liste aléatoire de températures : {temperatures}")

# Calcule la moyenne, la médiane et l'écart-type.
print(f"Moyenne des températures: {temperatures.mean().round(1)}")
print(f"Écart-type des températures: {temperatures.std().round(1)}")
print(f"Médiane des températures: {np.median(temperatures).round(1)}")


Liste aléatoire de températures : [26.60934073 21.5831766  27.8789688  25.46052044 16.41266022 29.63433527
 26.41709553 26.79096458 16.92170449 21.75578907 20.56197036 28.90147483
 24.6579768  27.3414242  21.65121298 18.40858083 23.31877181 15.95725884
 27.41446758 24.47496599 26.3713161  20.31788952 29.56047037 28.39681682
 26.67575246 17.91958062 22.00081506 15.65705649 17.31434238 25.2457343 ]
Moyenne des températures: 23.4
Écart-type des températures: 4.4
Écart-type des températures: 24.6


In [31]:
## module 2 ?

# Combien de jours sont au-dessus de 25 °C ?

# hot_day_amount = len(temperatures[temperatures > 25])
hot_day_amount = int((temperatures > 25).sum())
print(f"Il y a {hot_day_amount} jours >25°C.")

Il y a 14 jours >25°C.
[26.60934073 27.8789688  25.46052044 29.63433527 26.41709553 26.79096458
 28.90147483 27.3414242  27.41446758 26.3713161  29.56047037 28.39681682
 26.67575246 25.2457343 ]


In [39]:
# Remplace toutes les valeurs au-dessus de 28 °C par np.nan
temperatures[temperatures > 28] = np.nan
print(temperatures)

# puis recalcule la moyenne en ignorant les NaN.
# new_mean = temperatures[~np.isnan(temperatures)].mean().round(1)
new_mean = np.nanmean(temperatures).round(1)

print(f"Nouvelle moyenne (sans les temp > 28°C devenues NaN) : {new_mean} °C")

## en créant un nouveau tableau
temperatures_without_high = np.where(temperatures > 28, np.nan, temperatures)


[26.60934073 21.5831766  27.8789688  25.46052044 16.41266022         nan
 26.41709553 26.79096458 16.92170449 21.75578907 20.56197036         nan
 24.6579768  27.3414242  21.65121298 18.40858083 23.31877181 15.95725884
 27.41446758 24.47496599 26.3713161  20.31788952         nan         nan
 26.67575246 17.91958062 22.00081506 15.65705649 17.31434238 25.2457343 ]
Nouvelle moyenne (sans les temp > 28°C devenues NaN) : 22.5 °C


In [49]:
# Construis une matrice 5×6 d'entiers aléatoires entre 0 et 100
matrix = np.random.default_rng(42).integers(low=0, high=100, size=(5, 6))
print(matrix)

# et extrait la colonne 3 puis les lignes paires
third_column = matrix[:, 2]
pair_lines = matrix[1::2, :]

print(f"Colonne 3: {third_column}")
print(f"Lignes paires: {pair_lines}")


[[ 8 77 65 43 43 85]
 [ 8 69 20  9 52 97]
 [73 76 71 78 51 12]
 [83 45 50 37 18 92]
 [78 64 40 82 54 44]]
Colonne 3: [65 20 71 50 40]
Lignes paires: [[ 8 69 20  9 52 97]
 [83 45 50 37 18 92]]
